### ISSUE TITLE
Problem about malloc.c

### ISSUE THREAD

**Issue by Sm0ckingBird** [MRNIU/MiniCRT#1]
I think there are some bugs in the file mallo.c. For example, in the second case in function malloc(), `buf=malloc(1024*1024*32-32);`, buf turns out to be NULL. 

Actually, when I tried to implement this chapter, I found that there are a number of bugs in this chapter. If you also think so, maybe we could talk about it further.

Btw, I guess you run the project in 64-bit computer, `asm("movl %%rbp,(%0)    \n":"=r"(ebp_reg));` in the file entry.c could change to `asm("movq %%rbp,%0    \n":"=r"(ebp_reg));`.

**Comment by MRNIU** [comment]
@Sm0ckingBird 
hi, thanks for the issue, I will refactor this repo and fix that in days.

**Comment by Sm0ckingBird** [comment]
You are welcome. :)
